name: "dependency-report"
description: "Generate and submit dependency graph"
inputs:
  gradle-cache-encryption-key:
    description: "The encryption key for the Gradle cache."
    required: false
runs:
  using: composite
  steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
      if: "github.event_name != 'pull_request'"
      with:
        cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Generate and save dependency graph
      uses: gradle/actions/dependency-submission@v3
      if: "github.event_name == 'pull_request'"
      with:
        dependency-graph: generate-and-upload
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
