name: "run-gradle"
description: "Build and test the project"
inputs:
  snapshot-repo-url:
    description: "The URL of the maven repository"
    required: false
  release-repo-url:
    description: "The URL of the maven repository"
    required: false
  repo-username:
    description: "The username for the maven repository"
    required: false
  repo-password:
    description: "The password for the maven repository"
    required: false
  gradle-cache-encryption-key:
    description: "The encryption key for the gradle cache"
    required: false
  tests:
    description: "Whether to run tests"
    required: false
    default: "true"
  java-version:
    description: "The version of Java to use"
    required: false
    default: "11"
  tasks:
    description: "The gradle tasks to run"
    required: false
    default: "clean build"
  extra-args:
    description: "Extra arguments to pass to gradle"
    required: false
    default: ""
  use-nix-develop:
    description: "Whether to use nix develop for the action"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: configure shell
      id: shell-config
      env:
        CONFIGURED_SHELL: ${{ inputs.use-nix-develop == 'true' && 'nix develop --keep MAVEN_REPO_URL --keep MAVEN_REPO_USERNAME --keep MAVEN_REPO_PASSWORD -c bash -e {0}' || 'bash -e {0}' }}
      shell: bash
      run: 'echo "::set-output name=shell::$CONFIGURED_SHELL"'
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      if: ${{ inputs.use-nix-develop != 'true' }}
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}
        cache-cleanup: on-success
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
        add-job-summary-as-pr-comment: on-failure

    - name: Set version to sha
      id: sha-vars
      shell: bash
      if: "github.event_name != 'release'"
      run: echo "deploy_version=$(git rev-parse --short HEAD)-dev" >> $GITHUB_OUTPUT
    - name: Set version to release
      id: release-vars
      shell: bash
      if: "github.event_name == 'release'"
      run: echo "deploy_version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

    - name: Run gradle tasks
      shell: ${{ steps.shell-config.outputs.shell }}
      env:
        MAVEN_REPO_URL: ${{ github.event_name == 'release' && inputs.release-repo-url || inputs.snapshot-repo-url }}
        MAVEN_REPO_USERNAME: ${{ inputs.repo-username }}
        MAVEN_REPO_PASSWORD: ${{ inputs.repo-password }}
      run: ${{ inputs.use-nix-develop == 'true' && 'gradle' || './gradlew' }} ${{ inputs.tasks }} ${{ inputs.tests == 'true' && 'check' || '-x check -x test' }} -Pdeploy.version=${{ steps.release-vars.outputs.deploy_version || steps.sha-vars.outputs.deploy_version }} ${{ inputs.extra-args }} --console=plain --info --configure-on-demand --parallel --build-cache --configuration-cache

    - name: Generate a unique id
      id: gen-id
      shell: bash
      if: always()
      run: |
        echo "rand=$(openssl rand -hex 3)" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v4
      name: 'Upload reports'
      if: always()
      with:
        name: ${{ github.job }}-${{ steps.gen-id.outputs.rand }}-reports
        path: |
          ./build/reports
          ./**/build/reports
        retention-days: ${{ github.event_name == 'release' && 90 || 7 }}
