name: "jni-natives-ubuntu"
description: "Build jni natives on linux"
inputs:
  snapshot-repo-url:
    description: "The URL of the maven repository"
    required: false
  release-repo-url:
    description: "The URL of the maven repository"
    required: false
  repo-username:
    description: "The username for the maven repository"
    required: false
  repo-password:
    description: "The password for the maven repository"
    required: false
  gradle-cache-encryption-key:
    description: "The encryption key for the gradle cache"
    required: false
  tests:
    description: "Whether to run tests"
    required: false
    default: "true"
  java-version:
    description: "The version of Java to use"
    required: false
    default: "11"
  extra-gradle-args:
    description: "Extra arguments to pass to gradle"
    required: false
  platform:
    description: "The platform to build for"
    required: true
runs:
  using: composite
  steps:
    - name: Setup C++ environment
      shell: bash
      run: |
        sudo apt-get install -y cmake ninja-build gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libstdc++-12-dev-arm64-cross

    - uses: silenium-dev/actions/base/gradle@main
      with:
        snapshot-repo-url: ${{ inputs.snapshot-repo-url }}
        release-repo-url: ${{ inputs.release-repo-url }}
        repo-username: ${{ inputs.repo-username }}
        repo-password: ${{ inputs.repo-password }}
        gradle-cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}
        tests: ${{ inputs.tests }}
        java-version: ${{ inputs.java-version }}
        tasks: "clean build ${{ github.event_name != 'pull_request' && 'publish' || '' }}"
        extra-args: "-Pdeploy.kotlin=false -Pdeploy.native=true -Pdeploy.platform=${{ inputs.platform }} ${{ inputs.extra-gradle-args }}"
